# Generated by Django 2.1.3 on 2019-07-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('lahore', 'Lahore'), ('islamabad', 'Islamabad'), ('multan', 'Multan'), ('karachi', 'Karachi'), ('rawalpindi', 'Rawalpindi')], default='Lahore', max_length=6),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('pakistan', 'Pakistan')], default='Pakistan', max_length=6),
        ),
    ]
