# Generated by Django 2.0 on 2019-03-02 17:21

import accessories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accessories.models.upload_image_path),
        ),
    ]
