# Generated by Django 2.0 on 2018-10-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='camera',
            field=models.TextField(default='8MP'),
        ),
        migrations.AddField(
            model_name='product',
            name='connectivity',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='product',
            name='diplay',
            field=models.TextField(default=5.6),
        ),
        migrations.AddField(
            model_name='product',
            name='other_features',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.TextField(default=2.0),
        ),
        migrations.AddField(
            model_name='product',
            name='sound',
            field=models.TextField(default='good speakers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.TextField(default='2GB'),
        ),
    ]
