# Generated by Django 2.0 on 2019-03-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20181025_0948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='Products',
        ),
    ]
