# Generated by Django 2.1.3 on 2019-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20190710_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product',
            new_name='name',
        ),
    ]
