# Generated by Django 2.1.3 on 2019-07-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20190710_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='product',
        ),
    ]
