# Generated by Django 2.0 on 2019-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190302_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Charging',
            field=models.TextField(default='26000mAh'),
        ),
    ]
