# Generated by Django 2.0 on 2019-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_populrity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Knowledge_Score',
            field=models.FloatField(default=0.0),
        ),
    ]
