# Generated by Django 2.0 on 2019-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_knowledge_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Front',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Main',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Ram',
            field=models.TextField(),
        ),
    ]
