# Generated by Django 2.1.3 on 2019-04-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190422_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='Color',
            field=models.TextField(max_length=120),
        ),
    ]
