# Generated by Django 2.0 on 2019-07-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190702_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Ram',
            field=models.TextField(null=True),
        ),
    ]
