# Generated by Django 2.0 on 2019-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20190703_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='A_R',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='R_C',
            field=models.IntegerField(default=0),
        ),
    ]
