# Generated by Django 2.0 on 2019-06-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_charge_chargemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargeManager',
        ),
    ]
